spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:order_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:secret}

user:
  service:
    url: ${USER_SERVICE_URL:http://localhost:8080}
